embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
min_topic_size: 3
nr_topics: "auto"
top_n_words: 15
umap:
  n_neighbors: 15
  n_components: 5
  min_dist: 0.1
hdbscan:
  min_cluster_size: 3
  min_samples: 1
c_tf_idf:
  n_gram_range: [1, 3]
